
non_programming_related = ["Psychology", "Economics", "Business Administration", "Bachelor of Laws", "Medicine",
                           "Education", "Architecture", "Fine Arts", "Social Work", "Nursing",
                           "Mechanical Engineering", "Civil Engineering", "Environmental Science", "Political Science",
                           "International Relations", "Public Health", "Journalism", "Criminal Justice",
                           "Graphic Design", "Music", "Dentistry", "Veterinary Medicine", "Film Production",
                           "Fashion Design", "Hospitality Management", "Nutrition", "Animation", "Agriculture",
                           "Linguistics", "History", "Geology", "Philosophy", "Theater", "Dance", "Photography",
                           "Forensic Science", "Sociology", "Anthropology", "Marketing", "Finance", "Biotechnology",
                           "Aviation", "Sports Management", "Event Planning", "Acting", "Public Relations",
                           "Interior Design", "Industrial Design", "Counseling", "Library Science", "Geography",
                           "Religious Studies", "Urban Planning", "Hospital Administration",
                           "Early Childhood Education", "Physical Therapy", "Speech Therapy", "Occupational Therapy",
                           "Fashion Merchandising", "Culinary Arts", "Business Management",
                           "Human Resources Management", "Supply Chain Management", "Real Estate",
                           "Emergency Management", "Healthcare Administration", "Art Therapy", "Criminology",
                           "Robotics", "Sports Medicine", "Acting", "Public Relations", "Music Therapy",
                           "Fashion Illustration", "Visual Arts", "Art Education", "Human Nutrition", "Dietetics",
                           "Aquaculture", "Piloting", "Space Exploration", "Criminal Psychology", "Art History",
                           "Communication Studies", "Legal Studies", "Fashion Marketing", "Marine Biology",
                           "Disaster Management", "Peace Studies", "Archaeology", "Clinical Psychology",
                           "Food Science", "Medical Technology", "Interior Architecture", "Public Administration",
                           "Gerontology", "Medical Coding", "Medical Transcription", "Physical Education",
                           "Special Education", "Library and Information Science", "Horticulture", "Drama Therapy",
                           "Health Information Management", "Health Education", "Sustainable Development",
                           "Risk Management", "Hospitality and Tourism Management", "Sustainable Agriculture",
                           "Pharmacy", "Business Analytics", "Quantitative Finance", "Operations Management",
                           "Hospitality Administration", "Remote Sensing",
                           "Teaching English as a Second Language (TESL)",
                           "Teaching English as a Foreign Language (TEFL)",
                           "Teaching English to Speakers of Other Languages (TESOL)",
                           "Library and Information Science", "Urban and Regional Planning", "Ergonomics",
                           "Fashion Illustration", "Human Nutrition", "Dietetics", "Aquaculture", "Piloting",
                           "Space Exploration", "Criminal Psychology", "Art History", "Communication Studies",
                           "Legal Studies", "Fashion Marketing", "Marine Biology", "Disaster Management",
                           "Peace Studies", "Archaeology", "Clinical Psychology", "Food Science", "Medical Technology",
                           "Interior Architecture", "Public Administration", "Gerontology", "Medical Coding",
                           "Medical Transcription", "Physical Education", "Special Education",
                           "Library and Information Science", "Horticulture", "Drama Therapy",
                           "Health Information Management", "Health Education", "Sustainable Development",
                           "Risk Management", "Hospitality and Tourism Management", "Sustainable Agriculture",
                           "Pharmacy", "Business Analytics", "Quantitative Finance", "Operations Management",
                           "Hospitality Administration", "Remote Sensing",
                           "Teaching English as a Second Language (TESL)",
                           "Teaching English as a Foreign Language (TEFL)",
                           "Teaching English to Speakers of Other Languages (TESOL)",
                           "Library and Information Science", "Urban and Regional Planning", "Ergonomics",
                           "Fashion Illustration", "Human Nutrition", "Dietetics", "Aquaculture", "Piloting",
                           "Space Exploration", "Criminal Psychology", "Art History", "Communication Studies",
                           "Legal Studies", "Fashion Marketing", "Marine Biology", "Disaster Management",
                           "Peace Studies", "Archaeology", "Clinical Psychology", "Food Science", "Medical Technology",
                           "Interior Architecture", "Public Administration", "Gerontology", "Medical Coding",
                           "Medical Transcription", "Physical Education", "Special Education",
                           "Library and Information Science", "Horticulture", "Drama Therapy",
                           "Health Information Management", "Health Education", "Sustainable Development",
                           "Risk Management", "Hospitality and Tourism Management", "Sustainable Agriculture",
                           "Pharmacy", "Business Analytics", "Quantitative Finance", "Operations Management",
                           "Hospitality Administration", "Remote Sensing",
                           "Teaching English as a Second Language (TESL)",
                           "Teaching English as a Foreign Language (TEFL)",
                           "Teaching English to Speakers of Other Languages (TESOL)", "Urban and Regional Planning",
                           "Ergonomics", "Fashion Illustration", "Human Nutrition", "Dietetics", "Aquaculture",
                           "Piloting", "Space Exploration", "Criminal Psychology", "Art History",
                           "Communication Studies", "Legal Studies", "Fashion Marketing", "Marine Biology",
                           "Disaster Management", "Peace Studies", "Archaeology", "Clinical Psychology",
                           "Food Science", "Medical Technology", "Interior Architecture", "Public Administration",
                           "Gerontology", "Medical Coding", "Medical Transcription", "Physical Education",
                           "Special Education", "Library and Information Science", "Horticulture", "Drama Therapy",
                           "Health Information Management", "Health Education", "Sustainable Development",
                           "Risk Management", "Hospitality and Tourism Management", "Sustainable Agriculture",
                           "Pharmacy", "Business Analytics", "Quantitative Finance", "Operations Management",
                           "Hospitality Administration", "Remote Sensing",
                           "Teaching English as a Second Language (TESL)",
                           "Teaching English as a Foreign Language (TEFL)"]

programming_related = ["Computer Science", "Information Technology", "Software Engineering",
                       "Computer Engineering", "Data Science", "Web Development", "Mobile App Development",
                       "Database Management", "Network Administration", "Cybersecurity", "Artificial Intelligence",
                       "Machine Learning", "Deep Learning", "Natural Language Processing", "Computer Graphics",
                       "Human-Computer Interaction", "Cloud Computing", "Big Data Analytics",
                       "Blockchain Technology", "Internet of Things (IoT)", "Game Development", "DevOps",
                       "Full-Stack Development", "Frontend Development", "Backend Development", "UI/UX Design",
                       "Computer Programming", "Algorithm Design", "Operating Systems", "Parallel Computing",
                       "Computer Vision", "Parallel Computing", "Embedded Systems", "Information Security",
                       "Ethical Hacking", "Software Testing", "Quality Assurance", "Agile Development",
                       "Scrum Methodology", "Kotlin Programming", "Swift Programming", "JavaScript Programming",
                       "Python Programming", "Java Programming", "C++ Programming", "C# Programming",
                       "Ruby Programming", "PHP Programming", "HTML/CSS", "SQL", "React", "Angular", "Vue.js",
                       "Node.js", "Django", "Flask", "Spring Framework", "ASP.NET", "Ruby on Rails",
                       "WordPress Development", "Magento Development", "Drupal Development", "Unity Development",
                       "Unreal Engine Development", "iOS Development", "Android Development",
                       "Windows App Development", "Linux Development", "Embedded Linux Development",
                       "Raspberry Pi Development", "Arduino Development", "Cloud Infrastructure", "AWS",
                       "Microsoft Azure", "Google Cloud Platform", "Docker", "Kubernetes",
                       "Continuous Integration/Continuous Deployment (CI/CD)", "Version Control (Git, SVN)",
                       "Shell Scripting", "Bash Scripting", "PowerShell Scripting", "Perl Programming",
                       "Scala Programming", "Go Programming", "R Programming", "MATLAB Programming",
                       "Objective-C Programming", "Assembly Language", "VHDL Programming",
                       "Verilog Programming", "CUDA Programming", "Parallel Programming", "Functional Programming",
                       "TypeScript Programming", "GraphQL", "RESTful API Development", "Microservices Architecture",
                       "Serverless Computing", "Progressive Web Apps (PWA)", "Responsive Web Design",
                       "Cross-Platform Development", "Test-Driven Development (TDD)",
                       "Behavior-Driven Development (BDD)", "Web Assembly (WASM)", "Computer Forensics",
                       "Digital Forensics", "Malware Analysis", "Penetration Testing", "Incident Response",
                       "Reverse Engineering", "Network Security", "Cloud Security",
                       "Identity and Access Management (IAM)", "Security Operations Center (SOC)",
                       "Secure Software Development Lifecycle (SSDLC)", "Secure Coding Practices",
                       "Cybersecurity Frameworks", "Bug Bounty Hunting", "Capture The Flag (CTF) Competitions",
                       "Red Team/Blue Team Exercises", "Vulnerability Assessment",
                       "Security Information and Event Management (SIEM)", "Threat Intelligence",
                       "Zero Trust Architecture", "Data Encryption",  "Public Key Infrastructure (PKI)",
                       "Security Compliance", "Disaster Recovery Planning (DRP)",
                       "Business Continuity Planning (BCP)", "Risk Assessment",
                       "Regulatory Compliance (HIPAA, GDPR, etc.)", "IT Governance", "IT Audit",
                       "Secure Network Design", "Wireless Security", "IoT Security", "Cloud Security",
                       "Mobile Security", "Application Security", "Digital Identity Management", "Data Privacy",
                       "Cryptocurrency", "Smart Contracts", "Decentralized Applications (DApps)",
                       "Consensus Mechanisms", "Cryptographic Hash Functions", "Distributed Ledger Technology (DLT)",
                       "Smart Cities", "Connected Vehicles", "Industrial Internet of Things (IIoT)",
                       "Healthcare Informatics", "Telemedicine", "E-Health", "Electronic Medical Records (EMR)",
                       "Health Information Exchange (HIE)", "Telehealth", "Medical Imaging Informatics",
                       "Health Analytics", "Clinical Decision Support Systems (CDSS)",
                       "Personal Health Records (PHR)", "IoT in Healthcare", "Precision Medicine",
                       "Medical Device Connectivity", "Healthcare Interoperability", "Mobile Health (mHealth)",
                       "Social Media in Healthcare", "Health Informatics Standards",
                       "Health Information Technology (HIT)", "E-Learning", "Distance Learning",
                       "Massive Open Online Courses (MOOCs)", "Learning Management Systems (LMS)",
                       "Educational Technology", "Instructional Design", "Gamification in Education",
                       "Virtual Reality in Education", "Augmented Reality in Education", "Adaptive Learning",
                       "Mobile Learning", "Cloud-Based Learning", "Flipped Classroom",
                       "Open Educational Resources (OER)", "Digital Literacy", "Data Literacy", "Media Literacy",
                       "Information Literacy", "Computer Literacy", "Coding Literacy", "Online Safety",
                       "Privacy Protection", "Cybersecurity Awareness", "Ethical Hacking Awareness",
                       "Critical Thinking Skills", "Problem-Solving Skills", "Collaboration Skills",
                       "Communication Skills", "Creativity Skills", "Adaptability Skills", "Resilience Skills",
                       "Emotional Intelligence", "Leadership Skills", "Decision-Making Skills",
                       "Entrepreneurship Skills", "Financial Literacy", "Global Citizenship", "Cultural Competency",
                       "Intercultural Communication", "Language Skills", "Cross-Cultural Skills", "Teamwork Skills",
                       "Project Management Skills", "Time Management Skills", "Presentation Skills",
                       "Networking Skills", "Negotiation Skills", "Conflict Resolution Skills"]


def prepare_dataset(programming_related, non_programming_related):
    education_fields = programming_related + non_programming_related
    labels = [1] * len(programming_related) + [0] * len(non_programming_related)

    return education_fields, labels


education_fields, labels = prepare_dataset(programming_related, non_programming_related)

