

education_non_programm = [
    "Bachelor of Arts in Psychology, Harvard University, USA",
    "Bachelor of Science in Economics, London School of Economics and Political Science, UK",
    "Bachelor of Business Administration, Stanford University, USA",
    "Bachelor of Laws, University of Sydney, Australia",
    "Doctor of Medicine, Johns Hopkins University, USA",
    "Bachelor of Education, University of British Columbia, Canada",
    "Bachelor of Architecture, ETH Zurich, Switzerland",
    "Bachelor of Fine Arts, University of the Arts London, UK",
    "Bachelor of Social Work, University of Toronto, Canada",
    "Bachelor of Science in Nursing, Karolinska Institute, Sweden",
    "Bachelor of Mechanical Engineering, Massachusetts Institute of Technology (MIT), USA",
    "Bachelor of Civil Engineering, University of California, Berkeley, USA",
    "Bachelor of Environmental Science, Australian National University, Australia",
    "Bachelor of Political Science, Sciences Po, France",
    "Bachelor of International Relations, University of Tokyo, Japan",
    "Bachelor of Public Health, University of Melbourne, Australia",
    "Bachelor of Journalism, Columbia University, USA",
    "Bachelor of Criminal Justice, University of Cambridge, UK",
    "Bachelor of Graphic Design, Rhode Island School of Design (RISD), USA",
    "Bachelor of Music, Juilliard School, USA",
    "Bachelor of Dentistry, University of Toronto, Canada",
    "Doctor of Veterinary Medicine, University of California, Davis, USA",
    "Bachelor of Film Production, New York University (NYU), USA",
    "Bachelor of Fashion Design, Parsons School of Design, USA",
    "Bachelor of Hospitality Management, Cornell University, USA",
    "Bachelor of Nutrition, University of Sydney, Australia",
    "Bachelor of Animation, California Institute of the Arts (CalArts), USA",
    "Bachelor of Agriculture, Cornell University, USA",
    "Bachelor of Linguistics, University of Oxford, UK",
    "Bachelor of History, University of Cambridge, UK",
    "Bachelor of Geology, Stanford University, USA",
    "Bachelor of Philosophy, University of Chicago, USA",
    "Bachelor of Theater, Royal Academy of Dramatic Art (RADA), UK",
    "Bachelor of Dance, Paris Opera Ballet School, France",
    "Bachelor of Photography, School of the Art Institute of Chicago (SAIC), USA",
    "Bachelor of Forensic Science, University College London (UCL), UK",
    "Bachelor of Sociology, University of California, Los Angeles (UCLA), USA",
    "Bachelor of Anthropology, University of California, Berkeley, USA",
    "Bachelor of Marketing, Wharton School of the University of Pennsylvania, USA",
    "Bachelor of Finance, London Business School, UK",
    "Bachelor of Biotechnology, Massachusetts Institute of Technology (MIT), USA",
    "Bachelor of Aviation, Embry-Riddle Aeronautical University, USA",
    "Bachelor of Sports Management, University of Florida, USA",
    "Bachelor of Event Planning, George Washington University, USA",
    "Bachelor of Acting, Royal Academy of Dramatic Art (RADA), UK",
    "Bachelor of Public Relations, Syracuse University, USA",
    "Bachelor of Interior Design, Pratt Institute, USA",
    "Bachelor of Industrial Design, Rhode Island School of Design (RISD), USA",
    "Bachelor of Counseling, University of California, Santa Barbara, USA",
    "Bachelor of Library Science, University of Illinois at Urbana-Champaign, USA",
    "Bachelor of Geography, University of California, Santa Cruz, USA",
    "Bachelor of Religious Studies, Harvard University, USA",
    "Bachelor of Urban Planning, Massachusetts Institute of Technology (MIT), USA",
    "Bachelor of Hospital Administration, University of Michigan, USA",
    "Bachelor of Early Childhood Education, University of Melbourne, Australia",
    "Doctor of Physical Therapy, University of Pittsburgh, USA",
    "Master of Speech Therapy, University of Sydney, Australia",
    "Master of Occupational Therapy, University of Queensland, Australia",
    "Bachelor of Fashion Merchandising, Fashion Institute of Technology (FIT), USA",
    "Bachelor of Culinary Arts, Culinary Institute of America (CIA), USA",
    "Bachelor of Business Management, Harvard Business School, USA",
    "Bachelor of Human Resources Management, Cornell University, USA",
    "Bachelor of Supply Chain Management, University of Southern California (USC), USA",
    "Bachelor of Real Estate, London School of Economics and Political Science, UK",
    "Bachelor of Emergency Management, George Washington University, USA",
    "Bachelor of Healthcare Administration, University of Minnesota, USA",
    "Master of Art Therapy, New York University (NYU), USA",
    "Bachelor of Criminology, University of Cambridge, UK",
    "Bachelor of Robotics, Carnegie Mellon University, USA",
    "Doctor of Sports Medicine, Stanford University, USA",
    "Master of Music Therapy, Berklee College of Music, USA",
    "Bachelor of Fashion Illustration, Fashion Institute of Technology (FIT), USA",
    "Bachelor of Visual Arts, University of California, Los Angeles (UCLA), USA",
    "Bachelor of Art Education, School of the Art Institute of Chicago (SAIC), USA",
    "Bachelor of Human Nutrition, University of California, Berkeley, USA",
    "Bachelor of Dietetics, University of Sydney, Australia",
    "Bachelor of Aquaculture, University of Stirling, UK",
    "Bachelor of Piloting, United States Air Force Academy, USA",
    "Bachelor of Space Exploration, Massachusetts Institute of Technology (MIT), USA",
    "Bachelor of Criminal Psychology, University of Pennsylvania, USA",
    "Bachelor of Art History"]

education_programming = ["Computer Science", "Information Technology", "Software Engineering",
                         "Computer Engineering", "Data Science", "Web Development", "Mobile App Development",
                         "Database Management", "Network Administration", "Cybersecurity", "Artificial Intelligence",
                         "Machine Learning", "Deep Learning", "Natural Language Processing", "Computer Graphics",
                         "Human-Computer Interaction", "Cloud Computing", "Big Data Analytics",
                         "Blockchain Technology", "Internet of Things (IoT)", "Game Development", "DevOps",
                         "Full-Stack Development", "Frontend Development", "Backend Development", "UI/UX Design",
                         "Computer Programming", "Algorithm Design", "Operating Systems", "Parallel Computing",
                         "Computer Vision", "Parallel Computing", "Embedded Systems", "Information Security",
                         "Ethical Hacking", "Software Testing", "Quality Assurance", "Agile Development",
                         "Scrum Methodology", "Kotlin Programming", "Swift Programming", "JavaScript Programming",
                         "Python Programming", "Java Programming", "C++ Programming", "C# Programming",
                         "Ruby Programming", "PHP Programming", "HTML/CSS", "SQL", "React", "Angular", "Vue.js",
                         "Node.js", "Django", "Flask", "Spring Framework", "ASP.NET", "Ruby on Rails",
                         "WordPress Development", "Magento Development", "Drupal Development", "Unity Development",
                         "Unreal Engine Development", "iOS Development", "Android Development",
                         "Windows App Development", "Linux Development", "Embedded Linux Development",
                         "Raspberry Pi Development", "Arduino Development", "Cloud Infrastructure", "AWS",
                         "Microsoft Azure", "Google Cloud Platform", "Docker", "Kubernetes",
                         "Continuous Integration/Continuous Deployment (CI/CD)", "Version Control (Git, SVN)",
                         "Shell Scripting", "Bash Scripting", "PowerShell Scripting", "Perl Programming",
                         "Scala Programming", "Go Programming", "R Programming", "MATLAB Programming",
                         "Objective-C Programming", "Assembly Language", "VHDL Programming",
                         "Verilog Programming", "CUDA Programming", "Parallel Programming", "Functional Programming",
                         "TypeScript Programming", "GraphQL", "RESTful API Development", "Microservices Architecture",
                         "Serverless Computing", "Progressive Web Apps (PWA)", "Responsive Web Design",
                         "Cross-Platform Development", "Test-Driven Development (TDD)",
                         "Behavior-Driven Development (BDD)", "Web Assembly (WASM)", "Computer Forensics",
                         "Digital Forensics", "Malware Analysis", "Penetration Testing", "Incident Response",
                         "Reverse Engineering", "Network Security", "Cloud Security",
                         "Identity and Access Management (IAM)", "Security Operations Center (SOC)",
                         "Secure Software Development Lifecycle (SSDLC)", "Secure Coding Practices",
                         "Cybersecurity Frameworks", "Bug Bounty Hunting", "Capture The Flag (CTF) Competitions",
                         "Red Team/Blue Team Exercises", "Vulnerability Assessment",
                         "Security Information and Event Management (SIEM)", "Threat Intelligence",
                         "Zero Trust Architecture", "Data Encryption",  "Public Key Infrastructure (PKI)",
                         "Security Compliance", "Disaster Recovery Planning (DRP)",
                         "Business Continuity Planning (BCP)", "Risk Assessment",
                         "Regulatory Compliance (HIPAA, GDPR, etc.)", "IT Governance", "IT Audit",
                         "Secure Network Design", "Wireless Security", "IoT Security", "Cloud Security",
                         "Mobile Security", "Application Security", "Digital Identity Management", "Data Privacy",
                         "Cryptocurrency", "Smart Contracts", "Decentralized Applications (DApps)",
                         "Consensus Mechanisms", "Cryptographic Hash Functions", "Distributed Ledger Technology (DLT)",
                         "Smart Cities", "Connected Vehicles", "Industrial Internet of Things (IIoT)",
                         "Healthcare Informatics", "Telemedicine", "E-Health", "Electronic Medical Records (EMR)",
                         "Health Information Exchange (HIE)", "Telehealth", "Medical Imaging Informatics",
                         "Health Analytics", "Clinical Decision Support Systems (CDSS)",
                         "Personal Health Records (PHR)", "IoT in Healthcare", "Precision Medicine",
                         "Medical Device Connectivity", "Healthcare Interoperability", "Mobile Health (mHealth)",
                         "Social Media in Healthcare", "Health Informatics Standards",
                         "Health Information Technology (HIT)", "E-Learning", "Distance Learning",
                         "Massive Open Online Courses (MOOCs)", "Learning Management Systems (LMS)",
                         "Educational Technology", "Instructional Design", "Gamification in Education",
                         "Virtual Reality in Education", "Augmented Reality in Education", "Adaptive Learning",
                         "Mobile Learning", "Cloud-Based Learning", "Flipped Classroom",
                         "Open Educational Resources (OER)", "Digital Literacy", "Data Literacy", "Media Literacy",
                         "Information Literacy", "Computer Literacy", "Coding Literacy", "Online Safety",
                         "Privacy Protection", "Cybersecurity Awareness", "Ethical Hacking Awareness",
                         "Critical Thinking Skills", "Problem-Solving Skills", "Collaboration Skills",
                         "Communication Skills", "Creativity Skills", "Adaptability Skills", "Resilience Skills",
                         "Emotional Intelligence", "Leadership Skills", "Decision-Making Skills",
                         "Entrepreneurship Skills", "Financial Literacy", "Global Citizenship", "Cultural Competency",
                         "Intercultural Communication", "Language Skills", "Cross-Cultural Skills", "Teamwork Skills",
                         "Project Management Skills", "Time Management Skills", "Presentation Skills",
                         "Networking Skills", "Negotiation Skills", "Conflict Resolution Skills"]
